Bookstore: initialize project with components
ZuhRa-HashiMi/Bookstore pull request #1
Opened 2022-12-14 16:50 UTC by ZuhRa-HashiMi

Use React Router.
Use React components.

2022-12-14 17:13 UTC, mckent05 requested changes
Hi @ZuhRa-HashiMi, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 
- God job using the create-react-app command to initialize your project 👏 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-14 17:13 UTC, mckent05 commented on src/components/navBar.js
> +  </header>
- Good job done so far 👍 👍, but there are some issues with your navbar, your navbar should contain 2 links, a link that displays a list of books, and another link `categories` that should render a page showing a button `check status`. Please ensure that your nav has links that render the desired page 🙏 
- Also please remove the Math magician header currently displaying on your page, this is an `Bookstore` project, please fix this 👍 

Your Project:
<img width="960" alt="wtwtqhwhq" src="https://user-images.githubusercontent.com/73607512/207661635-26e74428-dfdd-45d7-b69c-c2f22a4361fc.PNG">

2022-12-14 17:13 UTC, mckent05 commented on src/components/bookList.js
> +    </ul>
**OPTIONAL**-I suggest you do not need to use a `ul` tag here. Please fix this 🙏 🙏

2022-12-15 07:24 UTC, DammyShittu requested changes
Hi @ZuhRa-HashiMi,

## Highlights
✔️ Descriptive PR
✔️ Passing linters
✔️ Good branch name

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-15 07:24 UTC, DammyShittu commented on src/components/navBar.js
> +            <Link to="/profile">Profile</Link>
- [ ] This profile link on the navbar is unnecessary as there is no component related to it. Kindly remove it as it is unneeded.

2022-12-15 07:24 UTC, DammyShittu commented on src/App.js
> +          <Route path="/categories" element={<Categories />} />
- [ ] I am unable to navigate to the categories component. As can see I have clicked the categories navbar link yet I am still on the Homepage. Kindly fix this.

  ![image](https://user-images.githubusercontent.com/54848363/207798004-e47fbb68-6750-40ef-b739-9e46db48c71b.png)

2022-12-15 10:09 UTC, MaganaAsiati approved these changes
# Status: Approved [✔️](https://emojipedia.org/check-mark/)
## Hi @ZuhRa-HashiMi  , I'm @MaganaAsiati , your reviewer for this PR  :wave: 
Great work on making the changes requested by a previous reviewer 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


<img src="https://media2.giphy.com/media/ByeYxURXxPyptxD2ta/giphy-downsized-medium.gif"/>


## Highlights
- Descriptive pull request :heavy_check_mark:👨🏻‍💻
- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:


## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
Cheers and Happy coding! 🤓 👏👏👏

2022-12-15 10:14 UTC, merged